Related to 6484244 ("When using NB 5.5 to start the appserver 9.1 pe, got javax.servlet.ServletException: PWC3037"):
Moved the check for non existing tld resource outside the
org.xml.sax.InputSource constructor, because that constructor does not
check its InputStream argument for null, causing the Digester, which
is supposed to parse the stream, to later throw this exception, which is
not very helpful:

Caused by: java.net.MalformedURLException
        at java.net.URL.<init>(URL.java:601)
        at java.net.URL.<init>(URL.java:464)
        at java.net.URL.<init>(URL.java:413)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:968)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:184)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:798)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:148)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1242)
        at com.sun.org.apache.commons.digester.Digester.parse(Digester.java:1548)
        at org.apache.catalina.startup.TldConfig.tldScanStream(TldConfig.java:679)
        at org.apache.catalina.startup.TldConfig.tldScanTld(TldConfig.java:722)
        ... 69 more


With this commit, the exception will be much clearer:

javax.servlet.ServletException: PWC3039: Invalid TLD resource path <tld_path>
        at org.apache.catalina.startup.TldConfig.tldScanTld(TldConfig.java:713)
        at org.apache.catalina.startup.TldConfig.execute(TldConfig.java:441)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:4897)


and should the admin team forget to bundle any TLD resources referenced
from their web.xml in the future (which has been the root cause for
6484244), the bug can be assigned to them much faster. :)

Tests run: QL


Original author: jluehe
Date: 2006-10-23 18:27:46+00:00

svn path=/trunk/; revision=625